asset_path: /home/cshen/drlr/IsaacLab/source/isaaclab_tasks/isaaclab_tasks/direct/shadow_hand_lit/assets/single_bottle/sr_model.urdf
usd_dir: /home/cshen/drlr/IsaacLab/source/isaaclab_tasks/isaaclab_tasks/direct/shadow_hand_lit/assets/single_bottle/usd
usd_file_name: sr_model.usd
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 0.0
merge_fixed_joints: false
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness: 0.0
    damping: 3.0
collider_type: convex_hull
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props:
  mass: 0.1
  density: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: true
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: 1000.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: 8
  solver_velocity_iteration_count: 0
  sleep_threshold: null
  stabilization_threshold: null
collision_props: null
activate_contact_sensors: true
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: false
  solver_position_iteration_count: 8
  solver_velocity_iteration_count: 0
  sleep_threshold: null
  stabilization_threshold: null
  fix_root_link: null
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-12-17 at 16:05:59.
##
